### ISSUE TITLE
Pull Request is not opened

### ISSUE THREAD

**Issue by hamza72x** [golangci/misspell#13]
https://github.com/golangci/misspell/compare/golangci:master...hamza72x:ignore-directories?expand=1

<img width="1037" alt="image" src="https://github.com/golangci/misspell/assets/121971027/2fae817a-0992-4598-a0f9-8f90515070ac">

**Comment by ldez** [comment]
I can't reproduce your issue with an account that has no rights on this repository.
There is no specific right to create a PR.
So the problem is not our repository.
