### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ccoVeille** [golangci/misspell#15]
I would like to thank you for maintaining golangci-lint, and took the decision to keep `misspell` maintained.

Thank you also for adding a way to provide a way for handing "correction" via golangci mispell linter via extra-words via https://github.com/golangci/golangci-lint/pull/4401

It would help people in doing things by their own.

By trying to achieve it on my project, I noticed a few things that I think that should be added to misspell.

I'm thinking about adding a few more item in DictAmerican (and so DictBritish) that are meaningful in Go ecosystem:

Here are a few examples

Here is marshalling conversion
https://github.com/golangci/misspell/blob/950f5d19e77066a2353d9a22e89f8f889d1d7012/words.go#L28977

I would like to add things like:
- marshaller <-> marshaller
- everything needed to support unmarshal* (currently not detected)

Tell me if you are interested, the changes are pretty small, but I prefer to ask before working on it, and getting a "no", during the review :smile:

**Comment by ldez** [comment]
Hello,

The list is generated based on usage frequency and different sources.

For now, I don't plan to change that (because it's the main approach of misspell design) to add extra words inside misspell, this is why I created `extra-words` inside golang-ci lint and not add words inside misspell.

**Comment by ccoVeille** [comment]
OK.

My point is that words.go wasn't updated for a while.

Thanks for replying me.

I'm closing this issue.

**Comment by silverwind** [comment]
> The list is generated based on usage frequency and different sources.

Where is the source of this generation and are contributions welcome there?
