### ISSUE TITLE
 v0.5.1 asset file names are incorrect

### ISSUE THREAD

**Issue by massongit** [golangci/misspell#20]
https://github.com/golangci/misspell/blob/f33d7fdd6dd3f230fbd45f2c6295dc69895c1313/install-misspell.sh#L110
The above code indicates that the file name of the asset used on machines with amd64 architecture ends with `64bit.tar.gz`.
However, in [v0.5.1](https://github.com/golangci/misspell/releases/tag/v0.5.1), asset file names are not created according to this rule.
Therefore, `install-misspell.sh` does not work properly.

**Comment by ldez** [comment]
fixed by 8e11bcac68fe3b4af23ae64bad74fd48d758f0e5

I updated the assets and the script.
