### ISSUE TITLE
`-i` not ignoring rules

### ISSUE THREAD

**Issue by luizkowalski** [golangci/misspell#8]
Hey! First of all, thanks for maintaining this fork!

I'm trying to ignore a couple of rules, but apparently, the `-i` flag is being ignore:

```shell
❯ ~/bin/misspell **/*.{rb,txt} -i "TEH"
...
not_cleared_spec.rb:235:41: "TEH" is a misspelling of "THE"
```

I tried different things like this:

```shell
❯ ~/bin/misspell **/*.{rb,txt} -i "TEH,teh,THE,the"
```
I still keep seeing the `TEH` rule

I'm using v0.4.1 on MacOS (M2)

**Comment by ldez** [comment]
Hello,


the flags should be placed before the path:
```console
$ misspell foo.txt -i "teh"
foo.txt:1:0: "Teh" is a misspelling of "The"
$
```

```console
$ misspell  -i "teh" foo.txt
$
```
